- asoh/models/ecm/advancedSOH.py
- tests/models/ecm/test_asoh.py
Fixes #21. Also includes a bit more testing to the ASOH, but we still need to exhaustively test the `update` functionality in there.
> ECM ASOH template fix

- README.md
> Fixing coverage badge

- .github/workflows/gh-pages.yml
- README.md
- dev/environment.yml
- docs/Makefile
- docs/conf.py
- docs/index.rst
- docs/make.bat
- docs/system-models.rst
- pyproject.toml
Use github pages to host docs made using sphinx.
> Initial commit of documentation

- docs/system-models.rst
- moirae/estimators/online/__init__.py
- moirae/estimators/online/kalman/unscented.py
- moirae/interface.py
- tests/estimators/online/test_joint_ukf.py
- tests/estimators/online/test_ukf.py
By making it possible to turn off transient states.
> Further remove the need for filters know about CellModel

- docs/estimator.rst
- docs/index.rst
- docs/make.bat
- moirae/estimators/online/__init__.py
- tests/estimators/online/test_joint_ukf.py
Fix a few things and improve the docs along the way
> Add tests for the partial transients

- moirae/__init__.py
- moirae/models/base.py
- moirae/models/ecm/components.py
- moirae/models/ecm/utils.py
- moirae/version.py
- tests/models/ecm/test_asoh.py
- tests/models/test_base.py
> Implement serialization to and from json

- moirae/estimators/online/__init__.py
- moirae/interface.py
- tests/test_interface.py
Also introduce a `parameterize` to the test so we can test new estimator types more easily
> Update toolkit interface to new OnlineEstimator

- docs/README.md
- docs/conf.py
- docs/index.rst
- docs/source/estimators.rst
- docs/source/interface.rst
- docs/source/models.rst
- docs/source/modules.rst
- docs/source/simulator.rst
- moirae/estimators/online/__init__.py
- moirae/estimators/online/filters/__init__.py
- moirae/estimators/online/filters/base.py
- moirae/estimators/online/filters/kalman/unscented.py
- moirae/estimators/online/joint.py
- moirae/interface.py
- moirae/models/__init__.py
- moirae/models/base.py
- moirae/models/ecm/__init__.py
- moirae/simulator.py
- pyproject.toml
Adds pages for autodocumentation with API. Minor changes to docstrings within source code if they did not parse correctly.
> Introduce API documentation

- moirae/interface.py
- notebooks/state-estimation-for-camp-cell.ipynb
- pyproject.toml
Also add a progress bar to interface
> Update CAMP cell example notebook

- moirae/estimators/online/dual.py
- moirae/estimators/online/filters/distributions.py
- moirae/estimators/online/joint.py
- moirae/estimators/online/utils/model.py
- tests/estimators/online/filters/test_distributions.py
- tests/estimators/online/test_dual_ukf.py
Implements normalization in dual framework, and provides an easy way to initialize an A-SOH-normalized dual UKF. Related to discussions in #59.
> Dual normalization

- docs/estimators/index.rst
- docs/estimators/online/conversions.rst
- docs/source/estimators.rst
- moirae/estimators/online/filters/base.py
- moirae/estimators/online/filters/conversions.py
> Document how to use conversion classes

- docs/extending.rst
- docs/index.rst
- docs/system-models.rst
- moirae/models/base.py
Cell models and all of their related components.
> Improve documentation for cell models

- docs/conf.py
- docs/index.rst
- docs/source/interface.rst
- docs/toolkit.rst
- moirae/estimators/offline/__init__.py
- moirae/estimators/offline/loss.py
- moirae/estimators/online/filters/distributions.py
- moirae/interface/__init__.py
- moirae/interface/hdf5.py
- notebooks/interface-with-battery-toolkit.ipynb
- pyproject.toml
- tests/conftest.py
- tests/test_interface.py
Adds ability to store each state estimation into an HDF5 file for later use.
> Store state estimates into an HDF5 file

- moirae/interface/__init__.py
- tests/conftest.py
- tests/test_interface.py
Enable running state estimates on datasets too large to fit in memory
> Stream from HDF5 file if path provided

- .github/workflows/python-package.yml
- dev/environment.yml
Fix some installation issues and make a timed test suite
> Repair CI runs

- moirae/estimators/offline/loss.py
- tests/estimators/offline/test_scipy.py
Change the name of the "dataset" attribute to "tables"
> Update for battdata v0.4.1

- moirae/models/thevenin/__init__.py
- moirae/models/thevenin/state.py
Ensures that we can work with the latest version of thevenin.
> Include coulomb efficiency in Thevenin ASOH

- .github/workflows/gh-pages.yml
Fix due to changes in the upload-artifact action
> Upgrade to latest upload action

- moirae/models/thevenin/__init__.py
- moirae/models/thevenin/state.py
A recent improvement to the Thevenin code
> Add hystersis to Thevenin ASOH

- .github/workflows/gh-pages.yml
Broken when we moved to the new upload action.
> Update version of to deploy-pages action

- docs/estimators/index.rst
> Fix typos in offline estimator

- moirae/extractors/ecm.py
- pyproject.toml
OCV must be monotonically increasing with SOC and
our current method does not enforce this
> Use isotonic regression for OCV fitting

- moirae/interface/__init__.py
- tests/test_interface.py
A function I end up running often when testing moirae with data in battery-data-toolkit formats.
> Add function for running model from data inside a dataset

- moirae/version.py
- pyproject.toml
- tests/test_version.py
> Switch from homebrew versioning to setuptools-scm

- moirae/models/base.py
- tests/models/test_base.py
> Raise error if parameter does not exist

- moirae/models/thevenin/__init__.py
- moirae/models/thevenin/state.py
- performance-tests/online/camp/thevenin/joint.py
- performance-tests/run-performance-test.py
- tests/models/test_thevenin.py
The Prediction interface of Thevenin is dramatically faster than the Model interface for our step-by-step solutions. See Thevenin's docs, https://thevenin.readthedocs.io/latest/examples/prediction_interface.html
> Use Thevenin's predictor interface

- moirae/estimators/offline/loss/__init__.py
- moirae/estimators/offline/loss/_base.py
- moirae/estimators/offline/loss/_meta.py
- moirae/interface/__init__.py
- moirae/models/base.py
- moirae/models/ecm/ins_outs.py
- tests/estimators/offline/test_objectives.py
- tests/models/test_thevenin.py
Make the class used to makes inputs/outputs from a battdat dataframe in the MSELoss configurable.
Also promoted "temperature" from an attribute that is specific in Moirae-ECM to one used in all models. We may revisit later. I'm punting for now because we don't have any models which don't use temperature.
> Allow using Thevenin with Offline Estimation

- moirae/interface/__init__.py
- tests/models/test_thevenin.py
So that we can run thevenin on battdat data
> Pass input/output types through battdat interface

- moirae/extractors/ecm.py
Minor changes so we can add the missing info from the new tagging systems in `batterry-data-toolkit`
> Rc extract add stage and steps

- moirae/extractors/ecm.py
- Allows user to provide initial SOC
- Ensures consistent identification of rests
> Fixing a couple of things on RC extraction

- moirae/models/thevenin/__init__.py
Update needed for thevenin v0.3
> Do not re-set the number of RC pairs 

- tests/estimators/offline/test_scipy.py
> Fix the random seed for diff_ev test

- moirae/interface/hdf5.py
- tests/test_interface.py
Since custom estimators can take up a lot of space, instead of saving the pickle on the HDF5 metadata, we switched to saving it on its own array, as to guarantee the estimator can always be easily written and read from the file.
Fixes #178
> Changed way estimator is stored
